name: Managed CI Workflow Deployer - Repo2
on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the MCI repository
        uses: actions/checkout@v3.3.0
        with:
          repository: Omkarprakashchavan/managed-ci-workflow
          path: managed-ci-workflow
      - name: Clone the MCI repository
        uses: actions/checkout@v3.3.0
        with:
          repository: Omkarprakashchavan/tarun-repo-config
          path: tarun-repo-config
          fetch-depth: 0
      - name: Set Job event name as environment variable
        run: |
          echo RUN_EVENT=${{ github.event_name }} >> $GITHUB_ENV
          echo GITHUB_APP_TOKEN=${{ secrets.GITHUB_TOKEN }} >> $GITHUB_ENV
      - name: Install Python modules
        env:
          GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install ruamel.yaml
          pip3 install pyyaml
          pip3 install requests
          pip3 install gitpython
          ls -lrt
          pwd
          echo "------------tarun-repo-config-------------------"
          ls -lart tarun-repo-config/
          echo "------------managed-ci-workflow-------------------"
          ls -lart managed-ci-workflow/
          ls -lrta
          python managed-ci-workflow/main.py
      - name: tree -h
        run: tree -h .
          
